## What is Python Numpy Array?
NumPy arrays are a bit like Python lists, but still very much different at the same time. For those of you who are new to the topic, let’s clarify what it exactly is and what it’s good for.

As the name says, a NumPy array is a central data structure of the numpy library. The library’s name is actually short for "Numeric Python" or "Numerical Python". A NumPy array is also called ndarray, which is short for n-dimensional array.

## Import NumPy Library
As well as any other libraries, we have to import NumPy library when using NumPy. Usually, we use np as the nickname of Numpy

In [1]:
import numpy as np

## Create a NumPy Array
Simplest way to create an array in Numpy is to use Python List.

In [2]:
APythonList = [1,9,8,3]

To convert python list to a numpy array by using the object np.array.

In [3]:
numpy_array_from_list = np.array(APythonList)

To display the contents of the list.

In [4]:
numpy_array_from_list

array([1, 9, 8, 3])

In practice, there is no need to declare a Python List. The operation can be combined.

In [5]:
a  = np.array([1,9,8,3])

**NOTE**: Numpy documentation states the use of np.ndarray to create an array. However, this the recommended method.

You can also create a numpy array from a Tuple.

## Mathematical Operations on an Array
You could perform mathematical operations like additions, subtraction, division and multiplication on an array. The syntax is the array name followed by the operation (+.-,\*,/) followed by the operand.

In [6]:
numpy_array_from_list + 10

array([11, 19, 18, 13])

This operation adds 10 to each element of the numpy array.

## Shape of Array
You can check the shape of the array with the object shape preceded by the name of the array. In the same way, you can check the type with dtypes.

In [7]:
import numpy as np
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


An integer is a value without decimal. If you create an array with decimal, then the type will change to float.

In [8]:
#### Different type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


## Two Dimension Array
You can add a dimension with a ","coma

Note that it has to be within the bracket []

In [9]:
### 2 dimension
c = np.array([(1,2,3),
              (4,5,6)])
print(c.shape)

(2, 3)


## Three Dimension Array
Higher dimension can be constructed as follows:

In [10]:
### 3 dimension
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

(2, 2, 3)


## Summary
Below, a summary of the essential functions used with NumPy.

|Objective|Code|
|-|-|
|Create array|array([1,2,3])|
|Print the shape|array([.]).shape|


---
# Basic Matrix Operation Using NumPy Array


In [53]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[10,20,30],[40,50,60]])

In [59]:
print(type(x))

<class 'numpy.ndarray'>


In [54]:
x + y

array([[11, 22, 33],
       [44, 55, 66]])

In [55]:
x - y

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [57]:
3 * x

array([[ 3,  6,  9],
       [12, 15, 18]])

In [58]:
x * y

array([[ 10,  40,  90],
       [160, 250, 360]])

---
# Basic Matrix Operation Using NumPy Matrix

NumPy has two type of matrix representations. One is NumPy array above, and the other is np.matrix.

In [63]:
z = np.matrix([[0, 1, 2], [3, 4, 5]])
print(z)

[[0 1 2]
 [3 4 5]]


In [64]:
print(type(z))

<class 'numpy.matrix'>


In [66]:
mat_x = np.matrix(x)
print(mat_x)

[[1 2 3]
 [4 5 6]]


In [67]:
print(type(mat_x))

<class 'numpy.matrix'>


Importantly, np.array can be considered to be a mathematically more natural list expression (compared to Python original list). Thus, np.array can express any dimension of array: vector, matrix, or tensor.  On the other hand, np.matrix is dedicated to matrix representations.

In [71]:
np_array1 = np.array([1,2,3]) # Vector
print(np_array1)
type(np_array1)

[1 2 3]


numpy.ndarray

In [74]:
np_matrix1 = np.matrix([1,2,3]) #Not Vector.  This is considered as 1x3 matrix.
print(np_matrix1)
type(np_matrix1)

[[1 2 3]]


numpy.matrix

In [75]:
np_array2 = np.array([[1,2,3],[4,5,6]]) # Matrix
print(np_array2)
type(np_array2)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [76]:
np_matrix2 = np.matrix([[1,2,3],[4,5,6]]) # Matrix
print(np_matrix2)
type(np_matrix2)

[[1 2 3]
 [4 5 6]]


numpy.matrix

In [81]:
np_array3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # Tensor
print(np_array3)
type(np_array3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [86]:
# np.matrix cannot make 3 or more dimensional tensors. 
# Thus the next code is an error.
np_matrix3 = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]]) # Tensor

ValueError: matrix must be 2-dimensional

## Difference between np.array and np.matrix

As explained above, np.matrix is dedicated to mathematical matrix (m x n matrix), while np.array is more flexible, which can represent vector, matrix, and tensor.

Thus np.matrix math operations are quite natural as mathematical matrix operation, while np.array math operations are not (although, np.array math operations are a bit more natural as mathematical operations, comapred to Python list operations).

However, the current version of NumPy (1.10 or later) allows us to use np.array matrix more naturally. So, basically you can use np.array for all vector, matrix, and tensor operations, and forget np.matrix (when you write your code).

---
# np.zeros() and np.ones() in Python

## What is np.zeros and np.ones?
You can create a matrix full of zeroes or ones using np.zeros and np.one commands respectively. It can be used when you initialized the weights during the first iteration in TensorFlow and other statistic tasks.

The syntax is:

### Numpy Zero or Zero Matrix
> numpy.zeros(shape, dtype=float, order='C')

### Numpy Ones

> numpy.ones(shape, dtype=float, order='C')

Here,

- Shape: is the shape of the array
- Dtype: is the datatype. It is optional. The default value is float64
- Order: Default is C which is an essential row style.

### Example numpy zero

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

### Example numpy zero with datatype

In [14]:
np.zeros((2,2), dtype=np.int16)

array([[0, 0],
       [0, 0]], dtype=int16)

### Example numpy one 2D Array with datatype

In [15]:
np.ones((1,2,3), dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

## Identity Matrix
To create an Identy Matrix, use np.eye:

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Tri Matrix
To create a Tri matrix, use np.tri

In [18]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

### 

In [60]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [61]:
np.arange()

array([], dtype=int32)

---
# np.reshape() and np.flatten() 

## Reshape Data
In some occasions, you need to reshape the data from wide to long. You can use the reshape function for this. The syntax is:

> numpy.reshape(a, newShape, order='C')

Here,

- a: Array that you want to reshape
- newShape: The new desires shape
- Order: Default is C which is an essential row style.

### Exampe of Reshape

In [21]:
e  = np.array([(1,2,3), (4,5,6)])
print('The original shape is:')
print(e)
print('\n')
print('After reshape')
e.reshape(3,2)

The original shape is:
[[1 2 3]
 [4 5 6]]


After reshape


array([[1, 2],
       [3, 4],
       [5, 6]])

## Flatten Data
When you deal with some neural network like convnet, you need to flatten the array. You can use flatten(). The syntax is:

> numpy.flatten(order='C')

Here,

- Order: Default is C which is an essential row style.

### Exampe of Flatten

In [22]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

---
# np.hstack() and np.vstack()

## What is hstack?
With hstack you can appened data horizontally. This is a very convinient function in Numpy. Lets study it with an example:

In [23]:
## Horitzontal Stack

f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


## What is vstack?
With vstack you can appened data vertically. Lets study it with an example:

In [24]:
## Vertical Stack

f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


## Generate Random Numbers
To generate random numbers for Gaussian distribution use

> numpy.random.normal(loc, scale, size)

Here

- Loc: the mean. The center of distribution
- scale: standard deviation.
- Size: number of returns

In [28]:
## Generate random nmber from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.26349774 4.36455497 4.2582286  5.734487   4.39440182 5.45380905
 5.22861726 5.41303731 5.64102604 5.1450504 ]


---
# np.asarray()

## Asarray
The asarray()function is used when you want to convert an input to an array. The input could be a lists, tuple, ndarray, etc.

### Syntax:

> numpy.asarray(data, dtype=None, order=None)[source]

Here,

- data: Data that you want to convert to an array
- dtype: This is an optional argument. If not specified, the data type is inferred from the input data
- Order: Default is C which is an essential row style. Other option is F (Fortan-style)

### Example:

Consider the following 2-D matrix with four rows and four columns filled by 1

In [29]:
A = np.matrix(np.ones((4,4)))

If you want to change the value of the matrix, you cannot. The reason is, it is not possible to change a copy.

In [30]:
np.array(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Matrix is immutable. You can use asarray if you want to add modification in the original array. Let's see if any change occurs when you want to change the value of the third rows with the value 2.

In [31]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


## Code Explanation:

- np.asarray(A): converts the matrix A to an array
- [2]: select the third rows

---
# np.arange()
## What is Arange?
You sometimes want to create values that are evenly spaced within a defined interval. For instance, you want to create values from 1 to 10; you can use numpy.arange() function.

Syntax:

> numpy.arange(start, stop,step) 

Here

- Start: Start of interval
- Stop: End of interval
- Step: Spacing between values. Default step is 1

### Example:

In [32]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If you want to change the step, you can add a third number in the parenthesis. It will change the step.

In [33]:
np.arange(1, 14, 4)	

array([ 1,  5,  9, 13])

---
# np.linspace() and np.logspace()
## Linspace
Linspace gives evenly spaced samples.

Syntax:

> numpy.linspace(start, stop, num, endpoint)

Here,

- Start: Starting value of the sequence
- Stop: End value of the sequence
- Num: Number of samples to generate. Default is 50
- Endpoint: If True (default), stop is the last value. If False, stop value is not included.
### Example:
For instance, it can be used to create 10 values from 1 to 5 evenly spaced.

In [34]:
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

If you do not want to include the last digit in the interval, you can set endpoint to false:

In [35]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

## LogSpace
LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as np.linspace.

Syntax:

> numpy.logspace(start, stop, num, endpoint)

### Example:

In [36]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

Finaly, if you want to check the byte size of an array, you can use itemsize:

In [37]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

---
# Indexing and Slicing NumPy Arrays

## ndexing and slicing
Slicing data is trivial with numpy. We will slice the matrice "e". Note that, in Python, you need to use the brackets to return the rows or columns

In [38]:
## Slice

e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


Remember with numpy the first array/column starts at 0.

In [40]:
## First column
print('First row:', e[0])

## Second column
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In Python, like many other languages,

- The values before the comma stand for the rows
- The value on the rights stands for the columns.
- If you want to select a column, you need to add : before the column index.
- : means you want all the rows from the selected column.

In [41]:
print('Second column:', e[:,1])

Second column: [2 5]


To return the first two values of the second row. You use : to select all columns up to the second:

In [42]:
## Second Row, two values
print(e[1, :2])

[4 5]


---
# NumPy Statistical Functions
NumPy has many  useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc., from the given elements in the array. The functions are explained as follows:

## Statistical function
Numpy is equipped with the robust statistical function as listed below:

|Function|NumPy|
|-|-|
|Min|np.min()|
|Max|np.max()|
|Mean|np.mean()|
|Median|np.median()|
|Standard deviation|np.std()|

Consider the following array as an example:

In [43]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.73061767 4.81408675 3.70788305 4.43647763 5.35517888 5.44302581
 4.40916488 4.94046663 5.26321401 5.26220057]


## Example

In [44]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

3.7078830546555612
5.443025810123281
4.836231588310202
4.877276689417239
0.5137254441248199


---
# np.dot(): Dot Product
## Dot Product
Numpy is powerful library for matrices computation. For instance, you can compute the dot product with np.dot.

Syntax

> numpy.dot(x, y, out=None)

Here,

- x,y: Input arrays. x and y both should be 1-D or 2-D for the function to work
- out: This is the output argument.For 1-D array scalar is returned. Other wise ndarray

### Example:

In [45]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

---
# NumPy Matrix Multiplication with np.matmul()
## Matrix Multiplication
The Numpu matmul() function is used to return the matrix product of 2 arrays. Here is how it works

1. 2-D arrays, it returns normal product
2. Dimensions > 2, the product is treated as a stack of matrix
3. 1-D array is first promoted to a matrix, and then the product is calculated

> numpy.matmul(x, y, out=None)

Here,

- x,y: Input arrays. scalars not allowed
- out: This is optional parameter. Usually output is stored in ndarray

### Example:

In the same way, you can compute matrices multiplication with np.matmul.


In [48]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]]
i = [[5,6],[7,8]]
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

## Determinant
Last but not least, if you need to compute the determinant, you can use np.linalg.det(). Note that numpy takes care of the dimension.

In [50]:
## Determinant 2*2 matrix
np.linalg.det(i)

-1.999999999999999